---
title: "Week 3"
author: "Matt Moocarme"
date: "June 12, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE,
                      cache = T,
                      message = FALSE,
                      comment = '',
                      echo = F)
```

```{r load_libraries}
library(readr)
library(dplyr)
library(tidyr)
library(Metrics)
library(caret)
library(stringr)
library(e1071)
```


```{r load_data}
train_data <- read_csv('../../Kaggle/ShelterAnimal/train.csv')
```
```{r clean_data}
DF <- train_data %>%
  select(-AnimalID, -DateTime)

## Names missing
sum(is.na(DF$Name)/nrow(DF))
length(unique(DF$Name))
head(table(DF$Name))

```

```{r}
pop_names_cat <- read.csv("data/top_100_cat_names.txt") 
pop_names_dog <- read.csv("data/top_100_dog_names.txt")   

pop_names_cat <- str_trim( as.character(pop_names_cat[, 2]) )
pop_names_dog <- str_trim( as.character(pop_names_dog[, 2]) )

DF <- DF %>%
 mutate(Name = ifelse(is.na(Name), "not_known", Name))
DF <- DF %>%
  mutate(PopNameD = AnimalType == "Dog" & Name %in% pop_names_dog) %>%
  mutate(PopNameC = AnimalType == "Cat" & Name %in% pop_names_cat) %>%
  mutate(PopName = ifelse(PopNameC | PopNameD, "yes", "no")) %>%
  mutate(PopName = ifelse(Name == "not_known", "not_known", PopName)) %>%
  select(-PopNameC, -PopNameD, -Name)
  
table(DF$PopName)
```


```{r}
length(unique(DF$Color))

#find unique words for color
un_col <- str_replace_all(DF$Color, "[^[:alpha:]]", " ")  %>%
  word() %>%
  table() 

un_col
un_col <- un_col[!un_col < 50]   
un_col_names <- names(un_col)

for(nnn in un_col_names){
  DF[, nnn] <- as.factor(str_detect(DF$Color, nnn))
}

DF$Color <- NULL
``` 

```{r}
#   Breed
length(unique(DF$Breed))
head(DF$Breed)

DF <- DF %>%
  mutate(BreedSH = factor( str_detect(Breed, "Shorthair")) ) %>%
  mutate(BreedL = factor( str_detect(Breed, "Long"))) %>%
  mutate(BreedD = factor( str_detect(Breed, "Domestic"))) %>%
  mutate(BreedMix = factor( str_detect(Breed, "Mix"))) %>%
  mutate(Breed2 = factor( str_detect(Breed, "/"))) %>%
  select(-Breed)

table(DF$BreedSH)
table(DF$BreedL)
table(DF$BreedD)
table(DF$BreedMix)
table(DF$Breed2)

head(DF)
```

```{r}
DF <- DF %>%
    mutate(AgeOnOutcome = 
      as.numeric( str_extract(AgeuponOutcome, "[:digit:]+") ) *
         str_detect(AgeuponOutcome, "year")*360 +
      as.numeric( str_extract(AgeuponOutcome, "[:digit:]+") ) *
        str_detect(AgeuponOutcome, "month")*30 +
      as.numeric( str_extract(AgeuponOutcome, "[:digit:]+") ) *
        str_detect(AgeuponOutcome, "week")*7 + 
      as.numeric( str_extract(AgeuponOutcome, "[:digit:]+") ) *
       str_detect(AgeuponOutcome, "day")*1)

DF$AgeuponOutcome <- NULL

#View(DF)

DF <- DF %>%
    mutate(AgeOnOutcome2 = AgeOnOutcome^2, 
           AgeOnOutcome12 = AgeOnOutcome^(1/2), 
           AgeOnOutcome3 = AgeOnOutcome^3, 
           AgeOnOutcome13 = AgeOnOutcome^(1/3))
```

```{r}
DF$OutcomeSubtype <- NULL
length(unique(DF$SexuponOutcome))
DF[, 1:4] <- lapply(DF[, 1:4], as.factor )
sapply(DF, is.factor)

# alive or not
DF_B <- DF %>%
  mutate(OutcomeType = OutcomeType %in% c("Adoption")) %>%
  mutate(OutcomeType = ifelse(OutcomeType, "yes", "no")) 
table(DF_B$OutcomeType)
```

```{r}
library(foreach)
library(doMC)
registerDoMC(2)

```

```{r}


source("data/train_lm.R")
## use debugSource to activate breakpoints
#debugSource("train_lm.R")

incl_var <- "(AnimalType + PopName + BreedSH + BreedL + BreedD + BreedMix + Breed2)"

form = str_c("~ " ,  str_c(names(DF_B)[-1], collapse = " + "), 
             "+ AgeOnOutcome:", incl_var,
             "+ AgeOnOutcome2:", incl_var,
             "+ AgeOnOutcome3:", incl_var,
             "+ AgeOnOutcome12:", incl_var,
             "+ AgeOnOutcome13:", incl_var) 
form.f <- as.formula(form)

res_LM <- train_lm(DF_B, error_est = "none", model = "glm", 
                   y_ind = 1, x_ind = 2:ncol(DF) , 
                   form.f = form.f)
names(res_LM)

# LEt us take first record in test as an example
#View(res_LM$train[1, ])

predict(res_LM$model, res_LM$train[1, ])

#Predicted Probability
predict(res_LM$model, res_LM$train[1, ] , type = "prob")

#actual::
res_LM$train[1, "outcome"]


trainPred <- predict(res_LM$model, res_LM$train)

confusionMatrix(trainPred, res_LM$train$outcome, positive = "yes")

# Predicted probabilities
trainPred <- predict(res_LM$model, res_LM$train, type = "prob")
#logLoss(trainPred,)
```


```{r}
source("data/make_ROC_curve.R")
ret <- make_ROC(res_LM)
best.cut.off <<- ret$best.cut.off
trainPred <<- ret$trainPred
confusionMatrix(ifelse(trainPred[, "yes"] > best.cut.off, "yes", "no"), 
                res_LM$train$outcome, positive = "yes")

# compare to default 0.5
confusionMatrix(ifelse(trainPred[, "yes"] > 0.5, "yes", "no"), 
                res_LM$train$outcome, positive = "yes")

# change parameters in train_lm file for AUC and parameter grid
source("data/train_lm.R")
res_rp <- train_lm(DF_B, error_est = "cv", model = "rpart", 
                   y_ind = 1, x_ind = 2:ncol(DF_B), par = F)
res_rp$model
confusionMatrix(res_rp$model)

# ROC 
ret <- make_ROC(res_rp)
best.cut.off <<- ret$best.cut.off
trainPred <<- ret$trainPred

confusionMatrix(ifelse(trainPred[, "yes"] > best.cut.off, "yes", "no"), 
                res_rp$train$outcome, positive = "yes")

```


```{r}
# change parameters in train_lm file for AUC and parameter grid
source("data/train_lm.R")
res_rf <- train_lm(DF_B, error_est = "oob", model = "rf", 
                   y_ind = 1, x_ind = 2:ncol(DF_B), par = F)

res_rf$model$finalModel

## See how number of trees affects Error
plot(res_rf$model$finalModel)

# ROC 
ret <- make_ROC(res_rf)
best.cut.off <<- ret$best.cut.off
trainPred <<- ret$trainPred

confusionMatrix(ifelse(trainPred[, "yes"] > best.cut.off, "yes", "no"), 
                res_rf$train$outcome, positive = "yes")

```


